-  name: Create a login user
   user:
      name: master
      groups: admin
      state: present
      shell: /bin/bash      # Defaults to /bin/bash
      system: no             # Defaults to no
      createhome: yes        # Defaults to yes
      home: /home/master
      generate_ssh_key: yes   # Defaults to /home/<username>
      ssh_key_type: ecdsa

- name: initialize the cluster
  command: sudo kubeadm init --pod-network-cidr=10.244.0.0/16

- name: ansible create directory for kube config 
  file:
    path: /home/master/.kube
    state: directory
    recurse: yes
    mode: 0755 
- name: Ansible copy file to remote server
  copy:
    src: /etc/kubernetes/admin.conf 
    dest:  /home/master/.kube/config
    remote_src: true
    owner: master

- name: install calico 
  become: yes
  become_user: master
  shell: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
